name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Set up PATH
      run: echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

    - name: Grant permissions
      run: |
        chmod +x gradlew

        chmod +x ./main/alpha-bleed
        chmod +x ./main/alphableed-linux.exe

    - name: Build and dexify mod jar file
      run: ./gradlew main:deployDex

    #- name: Upload built mod jar file
      #uses: actions/upload-artifact@v2.2.1
      #with:
        #name: ProjectUnity (zipped)
        #path: main/build/libs/ProjectUnityDexed.jar
