name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Set up PATH
      run: echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

    - name: General information
      run: |
        java --version
        d8 --version

#    - name: Crazy hack
#      run: |
#        rm -rf downgrader/assets/META-INF/gradle
#
#        mkdir downgrader/assets/META-INF/services
#        echo "unity.downgrader.Downgrader" > downgrader/assets/META-INF/services/javax.annotation.processing.Processor

    - name: Build and dexify mod jar file
      run: |
        chmod +x gradlew
        ./gradlew tools:proc mod:deploy mod:dex --no-daemon --info --stacktrace

    - name: Upload built mod jar file
      uses: actions/upload-artifact@v2.2.1
      with:
        name: Project Unity (zipped)
        path: mod/build/libs/ProjectUnity.jar
        retention-days: 3
